kevin-ghannoum/soen490

- backend/README.md
- backend/package-lock.json
>  [MINOR] Wrote first version of backend readme #14

- frontend/README.md
> [MINOR] First version of frontend readme #13

- backend/src/main/dto/Accounts/AccountDTOs.ts
- backend/src/main/routes/AccountRoute.ts
- backend/src/main/services/ClientAccountService.ts
- backend/src/test/services/ClientAccountService.test.ts
- frontend/public/index.html
- frontend/src/components/CreateBusinessAccount/CreateBusinessAccount.tsx
- frontend/src/components/CreateClientAccount/CreateClientAccount.tsx
- frontend/src/components/CreateClientAccount/CreateClientAccountStyle.tsx
- frontend/src/components/CreateClientAccount/CreateClientFormValidationSchema.ts
- frontend/src/dto/Accounts/AccountDTOs.ts
- frontend/src/dto/AddressDTOs.ts
- frontend/src/services/AccountAPI.ts
> [MAJOR] Implement create client account 

- backend/src/main/routes/AccountRoute.ts
- Change get request such that it returns a DTO without the password. 
closes #73
> [MINOR] Fixed bug where get and get all accounts would retrieve the password.

- backend/package-lock.json
- backend/src/test/services/BusinessAccountService.test.ts
- Mocked auth0 test for 1 test.
closes #93
> [PATCH] Fixed main build by mocking auth0 test.

- backend/src/main/routes/AccountRoute.ts
- handle case where entity not found. It will return 404 not found instead of crashing.
closes #90
> [PATCH] Fixed edge case for entity not found.

- backend/src/main/routes/LogHoursRoute.ts
- backend/src/main/routes/ProjectRoute.ts
- backend/src/main/services/AccountService.ts
- backend/src/main/services/AuthenticationService.ts
- backend/src/main/services/BusinessAccountService.ts
- backend/src/main/services/EmployeeAccountService.ts
- backend/src/main/services/LogHoursService.ts
- backend/src/main/services/ProjectService.ts
- backend/src/test/helpers/SequelizeMock.ts
- backend/src/test/services/BusinessAccountService.test.ts
- backend/src/test/services/BusinessService.test.ts
- backend/src/test/services/ClientAccountService.test.ts
- backend/src/test/services/EmployeeAccountService.test.ts
- backend/src/test/services/LogHoursService.test.ts
- backend/src/test/services/ProjectService.test.ts
- backend/src/test/services/SaleService.test.ts
- backend/src/test/services/SocialMediaPageService.test.ts
- backend/src/test/services/WorksOnService.test.ts
> [MINOR] Refactor code in backend Sprint 3. 

- backend/src/main/app.ts
- frontend/cypress.json
- frontend/cypress/fixtures/clientList.json
- frontend/cypress/fixtures/createProject.json
- frontend/cypress/fixtures/employeeList.json
- frontend/cypress/fixtures/getSingleProject.json
- frontend/cypress/fixtures/projectCreated.json
- frontend/cypress/fixtures/projectList.json
- frontend/cypress/fixtures/updateProject.json
- frontend/cypress/integration/createProject.spec.js
- frontend/cypress/integration/editProject.spec.js
- frontend/cypress/integration/viewProject.spec.js
- frontend/package.json
- frontend/src/components/Project/CreateProject.tsx
- frontend/src/components/Project/ViewProject.tsx
> [MAJOR] Implementing e2e test for project feature.

- frontend/.gitignore
- frontend/cypress/plugins/index.js
- frontend/cypress/support/index.js
- frontend/package-lock.json
- frontend/package.json
> [MINOR] Added code coverage for cypress frontend tests.

- backend/src/main/services/ClientAccountService.ts
- backend/src/test/services/ClientAccountService.test.ts
- frontend/src/components/CreateClientAccount/CreateClientAccount.tsx
> [MINOR] Integrated auth0 to create client.

- frontend/src/App.tsx
> [PATCH] Fixed bug where authorization was not set when logging in with refresh token. 

- backend/src/main/dto/TaskDTOs.ts
- backend/src/main/services/AssignedService.ts
- backend/src/main/services/TaskService.ts
- backend/src/test/services/AssignedService.test.ts
- backend/src/test/services/TaskService.test.ts
- frontend/cypress/fixtures/assignEdited.json
- frontend/cypress/fixtures/assignedCreated.json
- frontend/cypress/fixtures/getSingleTask.json
- frontend/cypress/fixtures/taskCreated.json
- frontend/cypress/fixtures/taskEdited.json
- frontend/cypress/fixtures/taskList.json
- frontend/cypress/fixtures/taskListDelete.json
- frontend/cypress/integration/Task_Management/createTask.spec.js
- frontend/cypress/integration/Task_Management/deleteTask.spec.js
- frontend/cypress/integration/Task_Management/editTask.spec.js
- frontend/cypress/integration/Task_Management/taskList.spec.js
- frontend/src/App.tsx
- frontend/src/components/Task/CreateTask.tsx
- frontend/src/components/Task/EditTask.tsx
- frontend/src/components/Task/TaskList.tsx
Reformat code and add e2e and repository tests
> [MAJOR] Added end to end and backend tests to Task Management.

- backend/src/main/middleware/JWTMiddleware.ts
- backend/src/main/routes/AccountRoute.ts
- backend/src/main/routes/AssignedRoute.ts
- backend/src/main/routes/AuthenticationRoute.ts
- backend/src/main/routes/LogHoursRoute.ts
- backend/src/main/routes/ProjectRoute.ts
- backend/src/main/routes/TaskRoute.ts
- backend/src/main/services/BusinessAccountService.ts
- backend/src/main/services/ClientAccountService.ts
- backend/src/main/services/EmployeeAccountService.ts
- backend/src/main/utils/UserUtils.ts
- backend/src/main/utils/utils.ts
- backend/src/test/services/TaskService.test.ts
- frontend/cypress/integration/Task_Management/createTask.spec.js
> [MINOR] Added restriction on the endpoints in the backend.

- backend/src/main/repositories/EmployeeAccountRepository.ts
- backend/src/main/routes/AccountRoute.ts
> [PATCH] Code Smell - Removed duplicate function.

- backend/src/main/migrations/20220107212440-add-task-status-enum.js
- backend/src/main/migrations/20220113235621-edit-task-projectId-required.js
- backend/src/main/services/TaskService.ts
- backend/src/test/services/TaskService.test.ts
- frontend/src/components/Task/CreateTask.tsx
- frontend/src/components/Task/CreateTaskFormValidationSchema.ts
closes #112 
Migrate your databases
> Bsong/task project nullable/#112

- frontend/src/components/Shared/PageNotFound.tsx
> [MINOR] Implemented error page UI

- backend/src/main/config/config.js
- backend/src/main/config/sequelize.ts
- backend/src/main/migrations/20220113235621-edit-task-projectId-required.js
> [MINOR] Switched production database to MySQL.

- backend/swagger/cirrusspark.yaml
> [Minor] Created Swagger for Account, Project, and Auth endpoints.

- backend/src/main/routes/CallRoute.ts
- backend/swagger/cirrusspark.yaml
> [MINOR] Created Swagger for Call endpoints.

- backend/src/main/routes/CallRoute.ts
- backend/swagger/cirrusspark.yaml
> [PATCH] Fixed swagger warnings

- backend/src/main/dto/InvoiceDTO.ts
- backend/src/main/dto/Transaction/TransactionDTO.ts
- backend/src/main/migrations/20211002181051-create-invoice.js
- backend/src/main/models/Invoice.ts
- backend/src/main/repositories/ProductionRepository.ts
- backend/src/main/repositories/WorksOnRepository.ts
- backend/src/main/routes/AccountRoute.ts
- backend/src/main/services/EmployeeAccountService.ts
- backend/src/main/services/InvoiceService.ts
- backend/src/main/services/TransactionService.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Transactions/CreateProduction.tsx
- frontend/src/components/Transactions/CreateProductionFormValidationSchema.ts
- frontend/src/components/Transactions/SingleProjectTransaction.tsx
- frontend/src/dto/InvoiceDTO.ts
- frontend/src/dto/ProjectDTOs.ts
- frontend/src/dto/TransactionDTOs.ts
> [MINOR] Improving transaction feature.

- backend/src/main/app.ts
- backend/src/main/dto/EventDTOs.ts
- backend/src/main/dto/InvitedDTOs.ts
- backend/src/main/migrations/20210930192706-create-event.js
- backend/src/main/migrations/20211001151849-create-invited.js
- backend/src/main/models/Account.ts
- backend/src/main/models/Event.ts
- backend/src/main/models/Invited.ts
- backend/src/main/repositories/EventRepository.ts
- backend/src/main/routes/EventRoute.ts
- backend/src/main/services/EventService.ts
> [MAJOR] Implemented backend endpoints for event management. 

- backend/src/test/services/EventService.test.ts
- backend/swagger/cirrusspark.yaml
> [MINOR] Implemented unit tests for Event Service and Updated Swagger.

- backend/src/main/app.ts
- backend/src/main/routes/NotificationRoute.ts
- backend/src/main/services/NotificationService.ts
- frontend/src/services/NotificationAPI.ts
Cherry pick of commit 9e03642ae68f52e1001e89959cec1e4124a0a861 from branch bsong/root-page/#163
> [MINOR] Implement getter for Notifications

- frontend/src/App.tsx
- frontend/src/components/FAQ/FAQ.tsx
- frontend/src/components/FAQ/FAQStyle.ts
closes #225 , closes #243 
Desktop format
Responsiveness
> [MINOR] Created the FAQ page.

- frontend/src/components/Calendar/EventCreationForm.tsx
- frontend/src/components/Calendar/MyCalendar.tsx
> [PATCH] Fixed calendar not rendering when no event

- frontend/cypress/fixtures/createEventResponse.json
- frontend/cypress/fixtures/eventList.json
- frontend/cypress/fixtures/singleEvent.json
- frontend/cypress/helpers/eventScheduleIntercept.js
- frontend/cypress/helpers/loginIntercept.js
- frontend/cypress/integration/Schedule_Meeting/confirmMeeting.spec.js
- frontend/cypress/integration/Schedule_Meeting/createMeeting.spec.js
- frontend/cypress/integration/Schedule_Meeting/deleteMeeting.spec.js
- frontend/cypress/integration/Schedule_Meeting/editMeeting.spec.js
- frontend/cypress/integration/Schedule_Meeting/viewMeeting.spect.js
- frontend/package-lock.json
- frontend/package.json
> [MINOR] Implemented e2e test for schedule meeting

- backend/src/main/migrations/20210929033455-create-account.js
- backend/src/main/models/Account.ts
- backend/src/main/routes/AccountRoute.ts
> [MINOR] Remove password from database.

- backend/src/main/migrations/20210929033455-create-account.js
- backend/src/main/models/Account.ts
- backend/src/main/routes/AccountRoute.ts
- frontend/src/components/CreateEmployee/CreateEmployee.tsx
> [PATCH] Fixed bug when creating employee account as a admin account.

- backend/src/main/services/BusinessAccountService.ts
- backend/src/main/services/ClientAccountService.ts
- backend/src/main/services/EmployeeAccountService.ts
- backend/src/test/services/BusinessAccountService.test.ts
- backend/src/test/services/ClientAccountService.test.ts
- backend/src/test/services/EmployeeAccountService.test.ts
close #201 
This is a simple email message without any design to it. The template should be an enhancement or something the stakeholder will figure out.
> [MINOR] Implemented sending credential during sign up via email

- backend/src/main/services/ClientAccountService.ts
- backend/src/main/services/EmployeeAccountService.ts
- backend/src/main/services/LogHoursService.ts
- frontend/src/components/Project/CreateProject.tsx
> [PATCH] Fixed code smell

- backend/swagger/cirrusspark.yaml
> [MINOR] Adding swagger rest Diagram #267

- frontend/src/components/Shared/LandingPage.tsx
> [MAJOR] Implement landing page

- frontend/src/components/Sidebar/Sidebar.tsx
closes #276 
I added the FAQ to the sidebar menu.
Sidebar menu - Admin
Sidebar menu - Employee
> [PATCH] Added a FAQ item to the sidebar menu.
